### ISSUE TITLE
R Build Warnings/Errors

### ISSUE THREAD

**Issue by benkeser** [benkeser/drtmle#20]
@nhejazi -- Mind checking out [these warnings and build errors](https://cran.r-project.org/web/checks/check_results_drtmle.html) when you have a minute?

**Comment by nhejazi** [comment]
Dependency issues...but I'm unable to reproduce them, on CI or locally. Seems like there's a reference to `data.table` (which I can't find a single call to anywhere) and `snow` which is not explicitly relied on since the relevant chunk is commented out in the vignette. (Could be ephemeral issues from the CRAN build system?) If not, one fix would be to add `snow` and `data.table` to `Suggests` (though this shouldn't be necessary). Will look into this some more soon.

**Comment by benkeser** [comment]
Yes, weird indeed. With the latest PR, I've dropped the dependency on `plyr`, which maybe will help. Not sure if we can recreate the CRAN test environment to reproduce the error and see if this fixes it though...

**Comment by benkeser** [comment]
@nhejazi When I build now on R-Hub, I get a warning that `snow` is superseded (by `parallel`, I gather). I've added `eval = FALSE` to the code chunk where we, in theory, "use snow" (even though it's all commented out). Do you think that will be sufficient?

**Comment by benkeser** [comment]
@nhejazi Still [build errors](https://cran.r-project.org/web/checks/check_results_drtmle.html) with v1.0.5. I'm sort of at a loss for what to do since we can't find an environment to reproduce these errors.  Any ideas?

**Comment by nhejazi** [comment]
@benkeser - I’d missed this originally but it seems like the Note about the snow package is triggered from a check of the Rd files so I think it can be avoided by changing all instances of snow::X to parallel::X (equivalently doSnow functions ought to be replaced by their doParallel analogs, based (on this comment](https://r.789695.n4.nabble.com/R-CMD-check-Uses-the-superseded-package-doSNOW-td4702990.html).

For v1.0.5 of the package, note that all of the errors have to do with a dependency issue that we hadn’t seen before (on the stringi package, https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/drtmle-00install.html, on Windows only), while on Linux systems (https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-gcc/drtmle-00check.html), the builds pass. It’s not clear to me why stringi would be needed or why it’s failing on CRAN machines but I don’t see it as an issue on our end.

**Comment by benkeser** [comment]
We don't have a `snow` instance in the documentation. The only place it appears is in the vignette, where we have it commented out and I added `eval = FALSE` to the code chunk. I have no idea why these builds are thinking that we need `snow`. `parallel` is already listed in Suggests. Not sure what else we can do. 

One of the errors in 1.0.4 was due to `stringi`, but I added it too Suggests in 1.0.5, but doesn't seem to resolve.

**Comment by nhejazi** [comment]
For the issue with snow and parallel, it’s probably safe to just disregard it since it’s only causing a Note now anyway.

Re: stringi, I don’t think it’s an issue on our end. From https://github.com/gagolews/stringi/issues/304 and https://github.com/gagolews/stringi/issues/313, I gather that the CRAN machines are not set up properly to compile packages from source (as required by stringi in the absence of a binary). Since the package was updated just yesterday (https://cran.r-project.org/web/packages/stringi/index.html), it might take CRAN another day or two until binaries are available, at which I’d guess the issue will go away.

**Comment by benkeser** [comment]
Sounds good. I'll leave the issue up for now and revisit when I get my next snarky note from CRAN threatening to take down the package.

**Comment by benkeser** [comment]
No snarky note was forthcoming
